// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "Log In",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "parameters": [
                    {
                        "description": "Create user request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/login.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/login.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Logged user profile",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/getprofile.GetUserResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/register": {
            "post": {
                "description": "Register a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "Create user request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/create.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/create.CreateUserResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/karyaukk/{id}": {
            "put": {
                "description": "Mengupdate karya UKK berdasarkan ID yang diberikan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KaryaUKK"
                ],
                "summary": "Update a KaryaUKK by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "KaryaUKK ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data karya UKK yang akan diupdate",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_karyaukk_update.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_karyaukk_update.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_karyaukk_update.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_karyaukk_update.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_karyaukk_update.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Menghapus karya UKK berdasarkan ID yang diberikan",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KaryaUKK"
                ],
                "summary": "Delete a KaryaUKK by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "KaryaUKK ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delete.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_karyaukk_delete.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_karyaukk_delete.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_karyaukk_delete.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/kategori-karya": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengembalikan list semua kategori karya",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kategori_karya"
                ],
                "summary": "Ambil semua kategori karya",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_getall.Response"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_getall.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Endpoint untuk membuat kategori karya baru",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kategori_karya"
                ],
                "summary": "Buat Kategori Karya",
                "parameters": [
                    {
                        "description": "Data kategori karya",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_create.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_create.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_create.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_create.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/kategori-karya/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengembalikan detail kategori karya berdasarkan UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kategori_karya"
                ],
                "summary": "Ambil kategori karya berdasarkan ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kategori ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_getbyid.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_getbyid.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_getbyid.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Hapus satu kategori karya berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kategori_karya"
                ],
                "summary": "Hapus Kategori Karya",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Kategori Karya",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_delete.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_delete.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_delete.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_kategorikarya_delete.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/review": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil semua review yang ada di database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Ambil Semua Review",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ukk-smkn2_features_review_getall.Response"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_getall.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Membuat data review untuk karya tertentu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Buat review baru",
                "parameters": [
                    {
                        "description": "Request body review",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_create.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_create.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_create.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_create.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/review/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil satu data review berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Ambil Review by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Review ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_getbyid.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_getbyid.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_getbyid.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengupdate data review berdasarkan ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review"
                ],
                "summary": "Update Review by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Review ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data review yang akan diupdate",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_update.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_update.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_update.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_update.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_update.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Hapus review berdasarkan ID",
                "tags": [
                    "review"
                ],
                "summary": "Hapus Review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Review ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_delete.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_delete.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_review_delete.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/role": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get list of all roles",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "Get All Roles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ukk-smkn2_features_role_getall.Response"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_role_getall.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "Create Role",
                "parameters": [
                    {
                        "description": "Role create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_create.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_create.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_create.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_create.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/role/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get single role by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "Get Role by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_role_getbyid.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_role_getbyid.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_role_getbyid.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a role by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "Delete Role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_role_delete.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_role_delete.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_role_delete.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_role_delete.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/siswa": {
            "get": {
                "description": "Mengambil semua data siswa",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "siswa"
                ],
                "summary": "Get All Siswa",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ukk-smkn2_features_siswa_getall.Response"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_getall.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/siswa/{id}": {
            "get": {
                "description": "Mengambil data siswa berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "siswa"
                ],
                "summary": "Get Siswa by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Siswa ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_getbyid.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_getbyid.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_getbyid.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Memperbarui data siswa dengan ID tertentu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "siswa"
                ],
                "summary": "Update Siswa by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Siswa ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body data siswa",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_update.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_update.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_update.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_update.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_update.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Menghapus data siswa berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "siswa"
                ],
                "summary": "Delete Siswa",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Siswa ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delete.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_delete.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_delete.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ukk-smkn2_features_siswa_delete.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "create.CreateUserRequest": {
            "description": "Create user request body",
            "type": "object",
            "properties": {
                "email": {
                    "description": "Your Email",
                    "type": "string"
                },
                "nama": {
                    "description": "Your Name",
                    "type": "string"
                },
                "password": {
                    "description": "Your Password",
                    "type": "string"
                }
            }
        },
        "create.CreateUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "create.CreateUserResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/create.CreateUserResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "delete.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "getprofile.GetUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "login.AuthRequest": {
            "description": "Login user request body",
            "type": "object",
            "properties": {
                "email": {
                    "description": "Your Email",
                    "type": "string"
                },
                "password": {
                    "description": "Your Password",
                    "type": "string"
                }
            }
        },
        "login.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "ukk-smkn2_features_karyaukk_delete.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_karyaukk_update.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_karyaukk_update.Request": {
            "type": "object",
            "properties": {
                "deskripsi": {
                    "type": "string"
                },
                "judul": {
                    "type": "string"
                },
                "kategori_id": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "siswa_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_karyaukk_update.Response": {
            "type": "object",
            "properties": {
                "deskripsi": {
                    "type": "string"
                },
                "judul": {
                    "type": "string"
                },
                "karya_id": {
                    "type": "string"
                },
                "kategori_id": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "siswa_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_kategorikarya_create.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_kategorikarya_create.Request": {
            "type": "object",
            "properties": {
                "nama": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_kategorikarya_create.Response": {
            "type": "object",
            "properties": {
                "kategori_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_kategorikarya_delete.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_kategorikarya_delete.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_kategorikarya_getall.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_kategorikarya_getall.Response": {
            "type": "object",
            "properties": {
                "kategori_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_kategorikarya_getbyid.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_kategorikarya_getbyid.Response": {
            "type": "object",
            "properties": {
                "kategori_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_review_create.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_review_create.Request": {
            "type": "object",
            "properties": {
                "karya_id": {
                    "type": "string"
                },
                "komentar": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_review_create.Response": {
            "type": "object",
            "properties": {
                "karya_id": {
                    "type": "string"
                },
                "komentar": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "review_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_review_delete.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_review_getall.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_review_getall.Response": {
            "type": "object",
            "properties": {
                "karya_id": {
                    "type": "string"
                },
                "komentar": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "review_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_review_getbyid.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_review_getbyid.Response": {
            "type": "object",
            "properties": {
                "karya_id": {
                    "type": "string"
                },
                "komentar": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "review_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_review_update.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_review_update.Request": {
            "type": "object",
            "properties": {
                "karya_id": {
                    "type": "string"
                },
                "komentar": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_review_update.Response": {
            "type": "object",
            "properties": {
                "karya_id": {
                    "type": "string"
                },
                "komentar": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "review_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_role_create.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_role_create.Request": {
            "type": "object",
            "properties": {
                "nama": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_role_create.Response": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_role_delete.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_role_delete.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_role_getall.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_role_getall.Response": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_role_getbyid.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_role_getbyid.Response": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_role_update.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_role_update.Request": {
            "type": "object",
            "properties": {
                "nama": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_role_update.Response": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_siswa_create.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_siswa_create.Request": {
            "type": "object",
            "properties": {
                "jurusan": {
                    "type": "string"
                },
                "kelas": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "nis": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_siswa_create.Response": {
            "type": "object",
            "properties": {
                "jurusan": {
                    "type": "string"
                },
                "kelas": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "nis": {
                    "type": "string"
                },
                "siswa_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_siswa_delete.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_siswa_getall.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_siswa_getall.Response": {
            "type": "object",
            "properties": {
                "jurusan": {
                    "type": "string"
                },
                "kelas": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "nis": {
                    "type": "string"
                },
                "siswa_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_siswa_getbyid.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_siswa_getbyid.Response": {
            "type": "object",
            "properties": {
                "jurusan": {
                    "type": "string"
                },
                "kelas": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "nis": {
                    "type": "string"
                },
                "siswa_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_siswa_update.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_siswa_update.Request": {
            "type": "object",
            "properties": {
                "jurusan": {
                    "type": "string"
                },
                "kelas": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "nis": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ukk-smkn2_features_siswa_update.Response": {
            "type": "object",
            "properties": {
                "jurusan": {
                    "type": "string"
                },
                "kelas": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "nis": {
                    "type": "string"
                },
                "siswa_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "your own API application",
	Description:      "Restful API using go fiber",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
